platform:
  - x86

install:
  - choco install -y nodist
  - set NODIST_X64=0
  - npm install -g gulp bower node-pre-gyp node-gyp@3.3.1
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - bower i
  - npm i
  - npm run client-build-win

artifacts:
  - path: build\client\prod\build\Setup.exe
  - path: build\client\prod\build\win32-package.tar.gz
